### ISSUE TITLE
error: Build input file cannot be found

### ISSUE THREAD

**Issue by ParityError** [objective-see/DylibHijackScanner#1]
When I try and build the project I get an error:

```
error: Build input file cannot be found: 'MachO/MachOParser/MachO.m' (in target 'DHS' from project 'DHS')
```

It appears the directory `/MachO/MachOParser/` and it's class `MachO` are not included in the project.

**Comment by objective-see** [comment]
Moved these files into the project making it now fully self-contained 
(Or they can be grabbed from: https://github.com/objective-see/Mach-O).
